---
- name: deploy web servers
  become: false
  gather_facts: true
  hosts: all
  tasks:
  - name: install apache web server
    yum:
      name: httpd
      state: latest
    become: true
  - name: enable and start apache web server
    service:
      name: httpd
      state: started
      enabled: true
    become: true
  - name: Change index.html on webservers
    copy:
      content: "{{ansible_hostname}} web server running"
      dest: /var/www/html/index.html
    notify: "restart httpd and debug"
    become: true
  
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
    listen: "restart httpd and debug"
    become: true
    register: httpd_restarted

  - name: debug httpd restarted
    debug:
      var: httpd_restarted
    listen: "restart httpd and debug"
